  services:
    postgres:
      container_name: postgr
      image: postgres
      healthcheck:
        test: [ "CMD", "pg_isready",  "-U", "postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      volumes:
        - ./postgres:/var/lib/postgresql/data
      ports:
        - 5450:5432




    app:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      env_file: .env
      ports:
        - 8000:8000
      depends_on:
        - postgres

        
